### ISSUE TITLE
Enable CI and Codecov

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/ConstrainedOptim.jl#3]
@pkofod can you enable Travis, Appveyor, and Codecov, please?

**Comment by pkofod** [comment]
Yes

**Comment by pkofod** [comment]
I think Travis is enabled already, or it should be

edit: see https://travis-ci.org/JuliaNLSolvers/ConstrainedOptim.jl

**Comment by pkofod** [comment]
done

**Comment by anriseth** [comment]
Sweet, thank you
